production:
  adapter: postgresql
  database: jaystash_prod
  pool: 5
  host: 198.199.109.47
  username: postgres
  password: slar177
  timeout: 5000

development:
  adapter: postgresql
  database: jaystash_dev
  pool: 5
  host: 198.199.109.47
  username: postgres
  password: slar177
  timeout: 5000

test:
  adapter: postgresql
  database: jaystash_test
  pool: 5
  host: 198.199.109.47
  username: postgres
  password: slar177
  timeout: 5000